# Generated by Django 3.2.16 on 2024-07-24 07:56

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0006_auto_20240722_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="image",
            field=models.ImageField(
                default=None,
                help_text="Обязательное поле",
                null=True,
                upload_to="recipes/images/",
                verbose_name="Изображение блюда",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user", django.db.models.expressions.F("following")),
                    _negated=True,
                ),
                name="not_same",
            ),
        ),
    ]
