# Generated by Django 3.2.16 on 2024-07-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="avatar",
            field=models.ImageField(
                default=None,
                help_text="Необязательно, допустимые форматы: jpg, png",
                null=True,
                upload_to="users/",
                verbose_name="Аватар пользователя",
            ),
        ),
    ]
